[package]
name = "tarsnap-lifespan"
version = "0.1.0"
authors = ["Antti Ajanki <antti.ajanki@iki.fi>"]

[dependencies]
chrono = "0.4"
regex = "1"
indoc = "0.2"
log = "0.4.3"
stderrlog = "0.4.1"
structopt = "0.2.10"
